### ISSUE TITLE
Unsupported OS

### ISSUE THREAD

**Issue by jhartlep** [Kubas556/insomnia-plugin-luna-theme#1]
Hi, is there a reason, why you do not support MacOS or Linux?
It would be great, if I could install this theme on my Mac

**Comment by jhartlep** [comment]
I just found the path for MacOS:
~/Library/Application Support/Insomnia/plugins/insomnia-plugin-luna-theme

**Comment by jhartlep** [comment]
Added PR for darwin support

**Comment by Kubas556** [comment]
thanks! To be hones, i would never thought someone will want this plugin, so i was not interested into adding more supported systems. 😅 I made this as fun project, and few months later i decided to publish it.

**Comment by jhartlep** [comment]
I try to get the path for linux as well. But at the moment I don't have access to a linux system.

**Comment by Kubas556** [comment]
I have linux, so i can try when i find some time

**Comment by Kubas556** [comment]
linux support added as well
